title:            Fresearch
tagline:          Your Stories Told
description:      An Online Collaborative Content Sharing Platform
#Comment out url when working locally to resolve base urls correctly
url: 

# Owner/author information
owner:
  name:           Fresearch
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          kigened@gmail.com
  twitter:               
  github:         fresearch       
  instagram:           
  dribbble:       
  disqus:         fresearch
  location:       "Eldoret, KE"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/fresearch/fresearch.github.io
    external: true
#  - title: Dennis Who?
#    url: http://denniskig.github.io
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Africa/Nairobi
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
